import { StyleSheet, Platform } from "react-native";

export const WHEEL_ITEM_HEIGHT = 44;
export const WHEEL_VISIBLE_ROWS = 5;
export const WHEEL_HEIGHT = WHEEL_ITEM_HEIGHT * WHEEL_VISIBLE_ROWS;

export const styles = StyleSheet.create({
  // Header
  header: { paddingHorizontal: 20, paddingBottom: 20, gap: 18 },
  headerTopRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: { color: "#fff", fontSize: 19, fontFamily: "Inter_700Bold" },
  headerSubtitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 12,
    fontFamily: "Inter_500Medium",
    marginTop: 2,
  },

  // Step tracker
  trackerRow: { flexDirection: "row", alignItems: "flex-start" },
  trackerNode: { alignItems: "center", width: 56, gap: 6 },
  trackerCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "transparent",
  },
  trackerCircleActive: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  trackerCircleIdle: {
    backgroundColor: "rgba(255,255,255,0.16)",
    borderColor: "rgba(255,255,255,0.3)",
  },
  trackerLabel: { fontSize: 10.5 },
  trackerLineWrap: { flex: 1, paddingTop: 15, paddingHorizontal: 2 },
  trackerLine: { height: 2, borderRadius: 1 },

  // Layout
  scroll: { padding: 16, paddingBottom: 24, gap: 16 },
  card: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 18,
    gap: 16,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  footer: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 28 : 16,
    borderTopWidth: 1,
  },

  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 2,
  },
  sectionIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  sectionTitle: { fontSize: 17, fontFamily: "Inter_700Bold" },
  sectionSubtitle: {
    fontSize: 12.5,
    fontFamily: "Inter_400Regular",
    marginTop: 1,
  },

  fieldLabel: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  pillWrap: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  pill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    shadowColor: "#000",
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  pillText: { fontSize: 13, fontFamily: "Inter_500Medium" },
  iconPillWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  iconPill: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1.5,
    position: "relative",
  },
  iconPillText: {
    fontSize: 13,
  },
  iconPillCheck: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  experienceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginTop: 4,
  },
  experienceCard: {
    width: "48%",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    gap: 8,
    position: "relative",
  },
  experienceLabel: {
    fontSize: 13,
  },
  experienceCheck: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 14,
    height: 14,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  laptopCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    gap: 8,
  },
  laptopLabel: {
    fontSize: 14,
  },
  termsRow: {
    flexDirection: "row",
    gap: 10,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "flex-start",
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  termsText: {
    flex: 1,
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    lineHeight: 19,
  },
  cancel: { fontSize: 13, fontFamily: "Inter_400Regular" },

  strengthTrack: {
    height: 5,
    borderRadius: 3,
    backgroundColor: "#e5e7eb",
    overflow: "hidden",
  },
  strengthFill: { height: "100%", borderRadius: 3 },
  strengthLabel: { fontSize: 11, fontFamily: "Inter_600SemiBold" },

  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderRadius: 12,
    height: 50,
  },
  countryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
  },
  flagText: { fontSize: 18 },
  dialText: { fontSize: 14, fontFamily: "Inter_600SemiBold" },
  phoneDivider: { width: 1, height: 24 },
  phoneInput: {
    flex: 1,
    paddingHorizontal: 12,
    fontSize: 15,
    fontFamily: "Inter_400Regular",
    height: "100%",
  },
  errText: { fontSize: 12, fontFamily: "Inter_500Medium", color: "#ef4444" },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    maxHeight: "78%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingBottom: 20,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#ccc",
    alignSelf: "center",
    marginTop: 10,
    marginBottom: 6,
  },
  modalTitle: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    paddingHorizontal: 20,
    paddingBottom: 2,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    paddingHorizontal: 20,
    paddingBottom: 8,
    textAlign: "center",
  },
  countryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  countryName: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },

  dobBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1.5,
    borderRadius: 12,
    height: 54,
    paddingHorizontal: 10,
  },
  dobIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  dobText: { flex: 1, fontSize: 14, fontFamily: "Inter_500Medium" },
  ageBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 20 },
  ageBadgeText: { color: "#fff", fontSize: 11, fontFamily: "Inter_700Bold" },
  dobFooterRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
    marginTop: 14,
  },
  dobCancelBtn: {
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },

  // Wheel date picker
  wheelRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: WHEEL_HEIGHT,
    position: "relative",
  },
  wheelHighlight: {
    position: "absolute",
    left: 12,
    right: 12,
    top: WHEEL_ITEM_HEIGHT * Math.floor(WHEEL_VISIBLE_ROWS / 2),
    height: WHEEL_ITEM_HEIGHT,
    borderRadius: 12,
    borderWidth: 1,
  },
  wheelFadeTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: WHEEL_ITEM_HEIGHT * 1.4,
  },
  wheelFadeBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: WHEEL_ITEM_HEIGHT * 1.4,
  },
  wheelItem: {
    height: WHEEL_ITEM_HEIGHT,
    alignItems: "center",
    justifyContent: "center",
  },
  wheelItemText: { fontSize: 16 },

  // Faculty grid
  facultyScroll: {
    marginHorizontal: -20,
  },
  facultyScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 4,
  },
  facultyGridContainer: {
    flexDirection: "column",
    gap: 10,
  },
  facultyRow: {
    flexDirection: "row",
    gap: 10,
  },
  facultyCard: {
    width: 180,
    minHeight: 110,
    borderWidth: 1.5,
    borderRadius: 16,
    padding: 12,
    gap: 8,
  },
  facultyIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  facultyLabel: { fontSize: 12.5, lineHeight: 16 },
  facultyCheck: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },

  deptBox: { borderWidth: 1, borderRadius: 16, padding: 14, gap: 12 },
  deptHead: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  deptHeadText: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  deptCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  deptCardText: {
    fontSize: 13.5,
    flex: 1,
    paddingRight: 10,
    lineHeight: 18,
  },
  deptRadioCircle: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  deptRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },

  // Level meter
  levelRow: { flexDirection: "row", alignItems: "flex-start" },
  levelNode: { alignItems: "center", gap: 5, width: 48 },
  levelCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  levelLine: { flex: 1, height: 2, marginTop: 15, borderRadius: 1 },
  pgChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    borderWidth: 1,
  },

  // Semester toggle
  semesterCard: {
    flex: 1,
    borderWidth: 1.5,
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  semesterBadge: {
    width: 26,
    height: 26,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },

  reviewCard: { borderWidth: 1, borderRadius: 14, padding: 14, gap: 8 },
  reviewCardHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  reviewCardTitle: { fontSize: 14, fontFamily: "Inter_700Bold" },
  reviewEdit: { fontSize: 13, fontFamily: "Inter_600SemiBold" },
  reviewRow: { flexDirection: "row", justifyContent: "space-between", gap: 12 },
  reviewLabel: { fontSize: 12, fontFamily: "Inter_500Medium" },
  reviewValue: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    flexShrink: 1,
    textAlign: "right",
  },
});
